#ifndef WIFICONTROLLER_PROTOCOLS_H_
#define WIFICONTROLLER_PROTOCOLS_H_

#define MESSAGE_MARKER_SIZE 2
#define MESSAGE_BEGIN_MARKER "+_"
#define MESSAGE_END_MARKER "*_"

#define MESSAGE_MAX_SIZE 1024

#define CONNECT_TIMEOUT_MS 30000

#define STR_RESET "RESET"
#define STR_CONNECT_STATION "CONNECT_STATION"
#define STR_SETUP_ACCESS_POINT "SETUP_ACCESS_POINT"
#define STR_SSID "SSID"
#define STR_PASSWORD "PASSWORD"
#define STR_CONFIGURE_LAYOUT "CONFIGURE_LAYOUT"
#define STR_UPDATE_DATA "UPDATE_DATA"

#define STR_CONFIRM "OK"
#define STR_FAIL "FAIL"
#define STR_IP "IP"
#define STR_ACTION "ACTION"

#endif /* WIFICONTROLLER_PROTOCOLS_H_ */
